theme:
  grey:
    grey0: '#323232' # foreground
    grey1: '#8A8A8A' # comment
    grey2: '#AAAAAA' # selection
    grey3: '#C0C0C0' # background
    grey4: '#B8B8B8' # current line
    grey5: '#CFCFCF' # some very bright things, like label for INSERT mode 
  blue:
    blue0: '#2C4A83'
  red:
    red0: '#9A3E3E'
    red1: '#FAA6A6'
  yellow: 
    yellow0: '#978B78'
    yellow1: '#FFE8C4'
  green: 
    green0: '#2A5B3D'
    green1: '#9BB8A7'

